version: '3.7'

services:
  devops-ui:
    container_name: devops-ui
    hostname: devops-ui
    image: devops-ui:5.1.2.0
    ports:
      - 38080:80
    restart: always
    depends_on:
      - devops
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      darwin:
        aliases:
          - devops-ui
    logging:
      driver: json-file
      options:
        max-file: '7'
        max-size: 100m

  devops:
    container_name: devops
    hostname: devops
    image: devops:5.1.2.0
    restart: always
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    environment:
      PROMADDRESS: prom:9090
      DBHOST: 192.168.0.4:27017
      DBNAME: Darwin-DevOps
      DBUSER: ''
      DBPASSWORD: ''
    volumes:
      - ./prom/conf:/app/prom
    networks:
      darwin:
        aliases:
          - devops
    logging:
      driver: json-file
      options:
        max-file: '7'
        max-size: 100m

  prom:
    container_name: prom
    hostname: prom
    image: prom/prometheus:v2.29.2
    privileged: true
    ports:
      - 39090:9090
    volumes:
      - ./prom/conf:/etc/prometheus
      - ./prom/data:/prometheus
      - /etc/localtime:/etc/localtime
    command:
      - '--web.enable-lifecycle'
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    restart: always
    networks:
      darwin:
        aliases:
          - prom
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    logging:
      driver: json-file
      options:
        max-file: '7'
        max-size: 100m

networks:
  darwin:
    external: true
